name: build
on:
  push:
    branches:
      - main
      - /refs/heads/main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: checkout
        uses: actions/checkout@v2

      - name: go build
        run: |
          go build ./...
    
      - name: go test
        run: |
          go test -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
