##
## Quality checks
##
name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - go-update-deps
      - /refs/heads/go-update-deps

jobs:
  code:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false
