##
## Open PullRequest to update dependency
##
name: deps
on:
  push:
    branches:
      - update-deps
      - /refs/heads/update-deps

jobs:

  code:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
          source_branch: "update-deps"