##
## Open PullRequest to update dependency
##
name: deps
on:
  push:
    branches:
      - go-update-deps
      - /refs/heads/go-update-deps

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: diillson/auto-pull-request@v1.0.1
        id: open-pull-request
        with:
          destination_branch: "main"
          source_branch: "go-update-deps"
